### ISSUE TITLE
Split one ECV folder and use all sections in the Jupyter Book

### ISSUE THREAD

**Issue by crgoddard** [ecmwf-projects/c3s2-eqc-quality-assessment#180]
As discussed in the projections issue, there is a requirement from C3S to split the ECV hydro and cryo folders (if this is not a breaking change). 

At the same time we can activate the subsections in the Jupyter Book. They can be labelled as follows in the table of contents (overwriting the folder names):

- Atmosphere Physics
- Atmospheric Composition
- Land Biosphere
- Land Hydrology
- Cryosphere
- Ocean

Thanks!

@malmans2 , @jpmartins83

**Comment by malmans2** [comment]
Hi there, I'm on it. Do you want to simplify the subfolder names and use these?
`('Atmosphere_Physics', 'Atmospheric_Composition', 'Cryosphere', 'Land_Biosphere', 'Land_Hydrology', 'Ocean')`

If yes, one notebooks in main is affected:
```diff
- Satellite_ECVs/Atmospheric_composition_ECVs/satellite_satellite-methane_uncertainty_q01.ipynb
+ Satellite_ECVs/Atmospheric_Composition/satellite_satellite-methane_uncertainty_q01.ipynb
```

**Comment by malmans2** [comment]
My proposed changes are here: https://github.com/ecmwf-projects/c3s2-eqc-quality-assessment/pull/181
