### ISSUE TITLE
Figure numbering consistency/update

### ISSUE THREAD

**Issue by crgoddard** [ecmwf-projects/c3s2-eqc-quality-assessment#184]
Update needed to current figure number approach, as we will currently end up with figure numbers in the 100's (note how the seasonal forecast NB starts from 4, due to the three figures in Methane).

For climate projections they manually set the figure labels (Fig A etc), but I think that might also get messy (and the syntax is different).

My preference would be some way to reset the numbering per section or per assessment, but that will lead to labelling conflicts. Possibly this is okay if the labels are not used.

Once we decide, the template needs to be update!

**Comment by malmans2** [comment]
I looked at the email I sent you a couple of months ago, and it looks like the only option available is to use this kind of numbering: 1.1.1, 1.1.2, ... I.e., each notebook becomes a numbered section.

As you mentioned, jupyter-book does not allow to reset the numbering as it would not be able create a unique label to reference the the figure.

**Comment by crgoddard** [comment]
Lets test how that numbering would look, I think it would be better than what we have currently. If the labelling conflicts are not a critical error I would also be happy if we ignore them.

I see here that it looks possible to turn off numbering of different components: https://mystmd.org/guide/cross-references, and also choose where it starts - using frontmatter. I hoped we might be able to turn off the numbering across the book, and just turn it on for each assessment, but I couldn't get it to work.

The other option is manual numbering using [{figure.enumerator}](https://mystmd.org/guide/directives#directive-figure-enumerator).

**Comment by malmans2** [comment]
This is the relevant issue I think: https://github.com/jupyter-book/jupyter-book/issues/500

I tried various things when I looked into it, but I couldn't achieve what you need. Let's see how the 1.1.1 numbering looks like. I you don't like it, I think I can programmatically add the explicit enumeration when we build the book.

**Comment by malmans2** [comment]
Here is the PR so you can look at the preview: https://github.com/ecmwf-projects/c3s2-eqc-quality-assessment/pull/186

**Comment by crgoddard** [comment]
We've looked at this. If easy to implement it seems the preference is:

1. to keep the numbering of the sections and associated lists of notebooks, BUT
2. to reset the numbering of the figures in each notebook to just use one level programmatically. I guess we will avoid referencing conflicts as evaluators should use a static label anyway, in the cases where they do refer to figures in text. 

If 2 is non-trivial lets just go with the 3-level automatic numbering for now. I will update the guidance on the numbering in the template and notes, and update the figures in the projections notebooks.

**Comment by malmans2** [comment]
Hi @crgoddard,

I'm looking into 2, but it is not possible. The links you shared in your comments are not from the jupyter-book documentation.

These are the only parameters available: https://jupyterbook.org/en/stable/content/figures.html#figure-parameters

**Comment by crgoddard** [comment]
Ah, okay. I thought all Myst syntax would be available for jupyter book. Then I'll merge the pull request for now.

I suppose the alternative would be to just use images, with formatted text below for a caption. However the way it was done for projections with raw html is not ideal, as that might not render in an exported PDF etc.

![image](https://github.com/user-attachments/assets/ef9b1a18-8499-4995-99c9-f19caf951ec4)
