### ISSUE TITLE
Links to old cds no longer resolve

### ISSUE THREAD

**Issue by crgoddard** [ecmwf-projects/c3s2-eqc-quality-assessment#204]
There are often links to the dataset on the CDS within the notebooks (actually we encourage this).

Unfortunately they no longer work as the new CDS has a slightly different URL structure, e.g.:

OLD: https://cds.climate.copernicus.eu/cdsapp#!/dataset/projections-cmip6?tab=overview 
NEW: https://cds.climate.copernicus.eu/datasets/projections-cmip6?tab=overview

OLD: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-fire-burned-area?tab=overview
NEW: https://cds.climate.copernicus.eu/datasets/satellite-fire-burned-area?tab=overview

Manual fix required, or can we automate this by replacing all instances of '/cdsapp#!' with ''?

**Comment by crgoddard** [comment]
Great, I also noticed it changes from 'dataset' to 'datasets'. Not sure if there are any surprises for some datasets.

Also, if there are any other links to the old CDS we may need to fix them/replace them (like applications or datasets that did not get ported).

**Comment by malmans2** [comment]
See https://github.com/ecmwf-projects/c3s2-eqc-quality-assessment/pull/205

We can easily add more links pattern in the future. I've only implemented `cdsapp#!/dataset`, but we can easily add more patterns in the future.

**Comment by crgoddard** [comment]
It was good to set up a script for this, since all the in progress assessments will probably have the broken links. What is the best way to approve this, apply it every time we are going to merge to main?x

**Comment by malmans2** [comment]
It's a pre-commit, so just merge main into the branch you are working on.
If you forget about it, no big deal. The CI action will fail and we'll notice it.
