### ISSUE TITLE
Estimation of Caspian sea retreat using surface albedo_Last_Version

### ISSUE THREAD

**Issue by FaezehKarimian** [ecmwf-projects/c3s2-eqc-quality-assessment#245]
### Data Type

Satellite ECVs - Atmospheric Composition

### Assessment Category

consistency

### Dataset Name

satellite-albedo

### Question Number

3

### Workflow ID

eqctier3-61980bcc-1443-4e9f-8281-97637a678ec8

### Zipped Notebook

[Last_V_ALBEDO_Caspian sea.zip](https://github.com/user-attachments/files/17505598/Last_V_ALBEDO_Caspian.sea.zip)

### Environment

<details>

```
# Paste here
```

</details>

### Anything else we need to know?

Hi Mattia, 
Could you please provide the permalink for this updated version?
Thanks.

**Comment by malmans2** [comment]
Hi @FaezehKarimian,

> Could you please provide the permalink for this updated version?

Do you have an open issue for this notebook already?

**Comment by FaezehKarimian** [comment]
Hi @malmans2,
Member
[malmans2](https://github.com/malmans2), 
Yes, on June 7th, I had opened an issue. The issue can be found at "https://github.com/ecmwf-projects/c3s2-eqc-quality-assessment/issues/105#issue-2340410004", which I have attached.

**Comment by malmans2** [comment]
Then you should use that issue as explained in my comment: https://github.com/ecmwf-projects/c3s2-eqc-quality-assessment/issues/105#issuecomment-2158140494

I'm going to close this issue. Please send the new notebook in #105.
Also, please let me know if you have more duplicates as we would need to close some issues.

**Comment by FaezehKarimian** [comment]
Okay, sure. Thanks.

**Comment by FaezehKarimian** [comment]
Hi @malmans2 ,
Could you please provide the permalink for this updated version, which is based on the latest template? Also, could you confirm whether the figure captions are correctly formatted?
Thanks.

[Albedo_Usecase 3_Caspian Sea.zip](https://github.com/user-attachments/files/20440437/Albedo_Usecase.3_Caspian.Sea.zip)

**Comment by malmans2** [comment]
@FaezehKarimian this issue has been closed and and replaced by #105 and explained above
Please move your last comment in #105

**Comment by FaezehKarimian** [comment]
Hi @malmans2 ,
Could you please provide the permalink for this updated version?

[Albedo_Usecase 3_Caspian Sea .zip](https://github.com/user-attachments/files/22596108/Albedo_Usecase.3_Caspian.Sea.zip)

**Comment by malmans2** [comment]
This issue has been closed a long time ago. You need to use #105 as already mentioned in my previous comment.
